version: "3.9"

services:
  qresolve-api:

    build: .

    container_name: qresolve-api

    ports:
      - "8000:8000"

    volumes:
      - qresolve-db:/app/database

    restart: unless-stopped


volumes:
  qresolve-db: